apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-movieapi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapi-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieapi
  template:
    metadata:
      labels:
        app: movieapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "movieapi"
        dapr.io/app-port: "80"

    spec:
      containers:
      - name: main
        image: xximjasonxx/movieapi:arm-v1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: movieapi-service
spec:
  selector:
    app: movieapi
  ports:
  - port: 80
    targetPort: 80