apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: twitter-binding
  
spec:
  type: bindings.twitter
  version: v1
  metadata:
    - name: consumerKey
      secretKeyRef:
        name: sec-twitter
        key: consumerKey
    - name: consumerSecret
      secretKeyRef:
        name: sec-twitter
        key: consumerSecret
    - name: accessToken
      secretKeyRef:
        name: sec-twitter
        key: accessToken
    - name: accessSecret
      secretKeyRef:
        name: sec-twitter
        key: accessSecret