apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: account-statestore

spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-release-master.redis.svc.cluster.local:6379
    - name: redisPassword
      value: 5mtaULdjhs