apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountapi-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountapi
  template:
    metadata:
      labels:
        app: accountapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "accountapi"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: main
        image: xximjasonxx/accountapi:arm-v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: accountapi-service
spec:
  selector:
    app: accountapi
  ports:
  - port: 80
    targetPort: 80
