apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretapi-deploy
spec:
  selector:
    matchLabels:
      app: secretapi-pod
  template:
    metadata:
      labels:
        app: secretapi-pod
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "secret-api"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: secretapi-container
        image: xximjasonxx/secretapi:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
