apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-component
  namespace: dapr-state
  labels:
    app: redis-component
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: helm-redis-release-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  - name: enableTLS
    value: false
  - name: maxRetries
    value: 5